### ISSUE TITLE
Kreiranje dijagrama korištenja sustava

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#10]
[Dijagram slucajeva koristenja](https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/Dijagram%20slucajeva%20koristenja.md)

**Comment by MariaMispi** [comment]
![DijagramSlucajaKoristenja](https://user-images.githubusercontent.com/48434065/55754445-f838d800-5a4c-11e9-9312-4dc6aebc38b4.jpg)

**Comment by MariaMispi** [comment]
Profesor se autentificira u sustav te unosi podatke o biljnim vrstama. Profesor  može pretraživati, pregledavati i ažurriati podatke o biljnim vrstama.
Student može pretraživati i pregledavati podatke o biljnim vrstama.
Student ima mogućnost rješavanja kvizova te pregleda svojih rezultata.

Profesor:
1. Autentifikacija
2. Unos podataka o biljnim vrstama
3. Pretrazivanje podataka o biljnim vrstama
4. Pregled podataka o biljnim vrstama

Student/ostali korisnici:
1. Pretrazivanje podataka o biljnim vrstama
2. Pregled podataka o biljnim vrstama
3. Rjesavanje kvizova
4. Pregled tocno/netocnih odgovora

**Comment by MariaMispi** [comment]
[link] (https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/Dijagram%20slucajeva%20koristenja.md)

**Comment by MariaMispi** [comment]
[link!] (https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/Dijagram%20slucajeva%20koristenja.md)

**Comment by MariaMispi** [comment]
[Dijagram slucajeva koristenja.md!] (https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/Dijagram%20slucajeva%20koristenja.md)

**Comment by MariaMispi** [comment]
[Dijagram slucajeva koristenja.md] (https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/Dijagram%20slucajeva%20koristenja.md)

**Comment by vdavid033** [comment]
Done
