### ISSUE TITLE
Kreiranje grafičkog sučelja: mockup prozori za unos biljnih vrsta

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#11]

**Comment by tio-nio** [comment]
![Unos1](https://user-images.githubusercontent.com/48513147/55733729-a1b4a500-5a1e-11e9-9d0f-f92f8c45f2ef.png)
![ucitavanje_slika](https://user-images.githubusercontent.com/48513147/55733761-b002c100-5a1e-11e9-9ba4-e0b41f4d82b9.png)

**Comment by rkozlovic** [comment]
odličan prijedlog!

**Comment by tio-nio** [comment]
Dokumentacija/mockup_unos.md

**Comment by tio-nio** [comment]
[https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/mockup_unos.md](url)

**Comment by tio-nio** [comment]
https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/mockup_unos.md

**Comment by vdavid033** [comment]
Done
