### ISSUE TITLE
Kreiranje grafičkog sučelja: mockup prozori za pregled biljnih vrsta

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#12]
[Dokumentacija - Pregled prozora za pregled biljaka](https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/Mockup_pregled_biljnih_vrsta.md)

**Comment by MariaMispi** [comment]
![SnippingPregledPrep](https://user-images.githubusercontent.com/48434065/55734293-957d1780-5a1f-11e9-8059-8b0140843271.PNG)
![Izrezak88](https://user-images.githubusercontent.com/48434065/55734299-98780800-5a1f-11e9-829f-cee8a59ada06.JPG)
![Izrezak22](https://user-images.githubusercontent.com/48434065/55734301-99109e80-5a1f-11e9-87f5-0b97f042e55b.JPG)

**Comment by tcolic** [comment]
Kolegica Marija je odlično napravila mockup, pa je stoga naš mockup sličan njenom.
![Pregled biljaka](https://user-images.githubusercontent.com/49404299/55813627-5e753780-5aed-11e9-9855-13b23fda504c.png)
![Detaljan pregled biljaka](https://user-images.githubusercontent.com/49404299/55813638-646b1880-5aed-11e9-8b4a-d0be21512833.png)

**Comment by vdavid033** [comment]
Done
