### ISSUE TITLE
Kreiranje grafičkog sučelja: mockup prozori za provjeru znanja o biljnim vrstama

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#13]

**Comment by bmaracic** [comment]
![kvizMockupi](https://user-images.githubusercontent.com/48552045/55735393-87c89180-5a21-11e9-80e8-700e05571ef2.jpg)

**Comment by SamantaMalesic** [comment]
[Mockup prozori za provjeru znanja o biljnim vrstama](https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/mockup_provjeraznjanja.md)

**Comment by SaraMalesic** [comment]
[mockup prozori za provjeru znanja o biljnim vrstama](https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/Mockup_Provjera_znjanja.md)

**Comment by vdavid033** [comment]
Done
