### ISSUE TITLE
Kreiranje scenarija za svaki slučaj korištenja

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#14]
https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/scenarij%20koristenja.md

**Comment by bsvetlici** [comment]
Test

**Comment by bsvetlici** [comment]
Slučaj korištenja za Unos biljke, pregled biljke, kviz , ažuriranje biljke (brisanje, uređivanje)

**Comment by bsvetlici** [comment]
1.Klikom na gumb "Započni kviz" korisnik započinje kviz.
    Nasumično se generira pitanje prepoznavanje slike ili prepoznavanje naziva biljke. U slučaju prepoznavanja slike korisnik mora povezati sliku sa točnim hrvatskim i latinskim nazivima (drop down menu), odabrati uporabni dio i bioaktivnu tvar; a u slučaju prepoznavanja hrvatkog naziva korisnik mora povezati naziv sa točnom slikom, latinskim nazivom,te odabrati uporabni tio i bioaktivnu tvar.
    2.Klikom na gumb "Provjeri" dobija se povratna informacija o točnosti odgovora u obliku iksića ili kvačica u kvadratićima pored odgovora.
    3.Klikom na gumb "Dalje" generira se novo pitanje.
    4.Klikom na gumb "Završi" završava se kviz.

**Comment by rkozlovic** [comment]
izvrsna ideja!

**Comment by tonivkt** [comment]
Scenarij za slučaj korištenja
Unos podataka o biljnim vrstama
Autentifikacija
Pretraživanje podataka o biljnim vrstama
Pregled podataka  o biljnim vrstama
Ažuriranje/brisanje podataka o biljnim vrstama
Rješavanje kvizova
Pregled tocno netocno odgovorenih kvizova


Ažuriranje/brisanje podataka o biljnim vrstama
Glavni pravac:
1.	Odabire se odrežena biljka, red u tablici s biljkama.
2.	Otvara se određeni prozor s detaljima biljke iz pregleda podataka o biljnim vrstama klikom na tipku „prikaz“.
3.	U novom prozoru odabire se tipka „izbriši“ .
4.	Otvara se novi prozor za potvrdu brisanja.
5.	Potvrđujemo brisanje.
6.	Otvara se novi prozor s tekstom da je brisanje uspješno napravljeno.
7.	Vraćeni smo na prozor s pregledom svih biljnih vrsta.

Alternativni pravac:
1.	Starta na točki G2.
2.	U novom prozoru odabire se tipka „uredi“.
3.	Otvara se prozor s unosom podataka za tu biljku.
4.	Mjenjaju se podaci.
5.	Klikom na tipku „spremi“ spremaju se podaci.
6.	Otvara se novi prozor za potvrdu spremanja.
7.	Potvrđujemo spremanje.
8.	Otvara se novi prozor s tekstom da je spremanje uspješno napravljeno.
9.	Nastavak na G2.


Pregled podataka o biljnim vrstama
Glavni pravac:
1.	Odabire se odrežena biljka, red u tablici s biljkama.
2.	Otvara se određeni prozor s detaljima biljke iz pregleda podataka o biljnim vrstama klikom na tipku „prikaz“.
3.	Biljka se pregledava.
4.	Zatvara se prozor na tipku „zatvori“.
5.	Vraćeni smo na prozor s pregledom svih biljaka.

Alternativni pravac:
1.	Alternativni pravac za profesora: Ažuriranje i brisanje podataka o biljnim vrstama.

Pretraživanje podataka o biljnim vrstama
	Glavni pravac:
1.	Odabiremo tipku „prikaz biljaka“.
2.	Filtriramo i pretražujemo biljke pomoću filtera i polja za pretragu.
3.	Klikom na tipke „filtriraj“ i „pretraži“ prikazuju se odabrani rezultati.

Unos podataka o biljnim vrstama
	Glavni pravac:
1.	Odabire se tipka „unos biljaka“.
2.	Otvara se prozor za unos biljaka.
3.	Unose se biljke i podaci za biljku (sve osim slike).
4.	Dodaje se 5 slika.
5.	Klikom na tipku „spremi“ biljka se sprema.
6.	Polja za unos se resetiraju.
7.	Nastavljamo na G2.
Alternativni pravac:
1.	Nastavljamo na G4.
2.	Dodaje se još slika.
3.	Nastavljamo na G5.

Autentifikacija
	Glavni pravac:
1.	Prilikom otvaranja aplikacije otvara se prozor za prijavu.
2.	Unosi se korisničko ime i lozinka.
3.	Klikom na tipku „prijava“ ulazimo u aplikaciju.
Alternativni pravac:
1.	Nastavljamo na G2
2.	Otvara se prozor s tekstom „krivo korisničko ime ili lozinka“
3.	Nastavljamo na G2.

Rješavanje kvizova
1.	Klikom na gumb "Započni kviz" korisnik započinje kviz.
2.	Nasumično se generira pitanje prepoznavanje slike ili prepoznavanje naziva biljke. U slučaju prepoznavanja slike korisnik mora povezati sliku sa točnim hrvatskim i latinskim nazivima (drop down menu), odabrati uporabni dio i bioaktivnu tvar; a u slučaju prepoznavanja hrvatkog naziva korisnik mora povezati naziv sa točnom slikom, latinskim nazivom,te odabrati uporabni tio i bioaktivnu tvar.
3.	Klikom na gumb "Provjeri" dobija se povratna informacija o točnosti odgovora u obliku iksića ili kvačica u kvadratićima pored odgovora.
4.	Klikom na gumb "Dalje" generira se novo pitanje.
5.	Klikom na gumb "Završi" završava se kviz.

**Comment by toni4848** [comment]
[Dokumentacija/scenarij koristenja.md](url)

**Comment by tonivkt** [comment]
[https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/scenarij%20koristenja.md](https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/scenarij%20koristenja.md)

**Comment by bsvetlici** [comment]
g18

**Comment by SamantaMalesic** [comment]
Uočeno nekoliko pogrešaka u dijelu Rješavanje kvizova. 
**Ispravak:**
Alternativni pravac:
1.	Klikom na gumb "Započni kviz" korisnik započinje kviz.
2.	Nasumično se generira pitanje prepoznavanje po hrvatskom nazivu.
3.	Korisnik mora povezati hrvatski naziv sa točnom slikom, latinskim nazivom, botaničkom porodicom, te odabrati uporabni dio i bioaktivnu tvar.
4.	Nastavljamo na G4.

**Comment by vdavid033** [comment]
Done
