### ISSUE TITLE
Kreiranje dijagrama aktivnosti

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#15]
[Dijagram aktivnosti](https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/Dijagram%20aktivnosti.md)

**Comment by Nikola9900** [comment]
![STUDENT](https://user-images.githubusercontent.com/49404740/55759868-cd558080-5a5a-11e9-8da0-1baa00f89f47.jpg)
![PROFESOR](https://user-images.githubusercontent.com/49404740/55759870-cd558080-5a5a-11e9-8d31-86957c964157.jpg)

**Comment by bsvetlici** [comment]
![Pregled student dijagram toka](https://user-images.githubusercontent.com/49404552/55823544-36440380-5b02-11e9-9b84-33540d6ac353.jpg)

**Comment by tonivkt** [comment]
![Izrezak](https://user-images.githubusercontent.com/49404323/55823658-7c996280-5b02-11e9-850a-14500967e96c.JPG)

**Comment by IMilja** [comment]
![DijagramAktivnosti_Profesor](https://user-images.githubusercontent.com/26895298/55824571-655b7480-5b04-11e9-8dd4-dec3dd1527cd.png)

**Comment by vdavid033** [comment]
Done
