### ISSUE TITLE
Kreiranje modela podataka

### ISSUE THREAD

**Issue by tio-nio** [vdavid033/biljnevrste_repo#19]
![baza_biljnevrste](https://user-images.githubusercontent.com/48513147/56601350-2ac10400-65fb-11e9-8a5f-b7fff417580e.jpg)

**Comment by tio-nio** [comment]
https://github.com/vdavid033/biljnevrste_repo/blob/master/Dokumentacija/model_podataka.md

**Comment by tio-nio** [comment]
@rkozlovic copyright

**Comment by tio-nio** [comment]
[baza_biljnevrste.zip](https://github.com/vdavid033/biljnevrste_repo/files/3108774/baza_biljnevrste.zip)

visio file

**Comment by vdavid033** [comment]
Done!
