### ISSUE TITLE
U unosu je postavljen izraz biljna kategorija, pa ga treba razjasniti obzirom da se taj izraz ne može naći u dokumentima na Googlu.

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#2]
U unosu je postavljen izraz biljna kategorija, pa ga treba razjasniti obzirom da se taj izraz ne može naći u dokumentima na Googlu.

_Originally posted by @vdavid033 in https://github.com/vdavid033/biljnevrste_repo/issues/1#issuecomment-478617918_

**Comment by MariaMispi** [comment]
Biljna kategorija se ne koristi vec se odnosi na botanicku porodicu.

**Comment by SaraMalesic** [comment]
Jedna botanička porodica može imati više rodova.
