### ISSUE TITLE
Instalirati vue.js i podesiti početni ekran za pregled podataka

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#25]

**Comment by MariaMispi** [comment]
Vue.js 2.9.6
Python 3.7.3
Django 2.2

**Comment by MariaMispi** [comment]
Pozdrav,
Evo jedan ok tutorial kako instalirati Vue.js (provjeren):
Gledajte od podnaslova Bootstrapping the frontend Project do Creating an Auth0 API

https://auth0.com/blog/building-modern-applications-with-django-and-vuejs/

**Comment by vdavid033** [comment]
Quasar framework tutorial:
[Quasar Framework for Vue.js](https://www.youtube.com/watch?v=Ud8jS3VlVHw)

Mislim da ćete u njemu raditi. Vrlo je jednostavan za savladati i za kreirati sučelja. U tutorialu ima par stvari koje ne odgovaraju zbog verzija, pa pogledajte i službenu dokumentaciju:
[https://quasar-framework.org/guide/](https://quasar-framework.org/guide/)

_npm install -g vue-cli_
_npm install -g quasar-cli_
