### ISSUE TITLE
Postaviti Django/REST okruženje

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#37]
https://www.youtube.com/watch?v=D6esTdOLXh4&t=969s
Super je objašnjeno, pratite do 38:40.

**Comment by IMilja** [comment]
@vdavid033 Šta je točno potrebno kreirati? Samo REST urlove pomoću Django REST frameworka?

**Comment by vdavid033** [comment]
Za sad samo postavljanje okruženja, pogotovo za tek uključene. Ali da... REST

**Comment by IMilja** [comment]
Uredu... Dakle pripremiti sve za izradu RESTa u budućnosti... Hvala

**Comment by vdavid033** [comment]
[https://www.django-rest-framework.org/tutorial/quickstart/](https://www.django-rest-framework.org/tutorial/quickstart/)
