### ISSUE TITLE
Frontend setup i zadaci

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#46]
Frontend radite u Javascript frameworcima: Vue.js i Quasar

1. Preuzmite i instalirajte Node package manager (npm)
1. Instalirati Vue.js i Quasar
     npm install -g vue-cli
     npm uninstall -g quasar-cli
     npm install -g @quasar/cli
     Verzija 1.0: [https://v1.quasar-framework.org/quasar-cli/installation](https://v1.quasar-framework.org/quasar-cli/installation)
1. Quasar framework se naslanja na Vue.js i možete ga koristiti za kreiranje sučelja. Vrlo je jednostavan i brzo možete kroz programski kod dodavati komponente . Greške su vidljive odmah.
1. Quasar framework tutorijal (YouTube) koji obavezno pogledajte:
[Quasar Framework for Vue.js](https://www.youtube.com/watch?v=Ud8jS3VlVHw)
1. Službena Quasar dokumentacija:
[https://quasar-framework.org/guide/](https://quasar-framework.org/guide/)
U tutorijalu ima par stvari koje ne odgovaraju zbog verzija, pa pogledajte i službenu dokumentaciju
1. Podatke ćete moći dobiti preko REST API-ja, a za sad koristite primjer iz tutorijala.

Podjela zadataka:
@tio-nio dizajn svih prozora - ovaj dizajn će se koristiti u konačnici
@MariaMispi, @karolina444 - kreiranje ekrana za unos biljnih vrsta
@josipf09 - kreiranje ekrana za pregled biljnih vrsta
@SaraMalesic - kreiranje ekrana za prikaz biljke
@bmaracic, @Nikola9900 - kreiranje ekrana za kviz
@tcolic - testiranje
Ostale ekrane napravite prema mockupu, ali se ne zadržavajte na izgledu, nego dodajte akcije i vidite koji podaci iz baze vam trebaju da biste mogli koristiti: što ćete poslati i što trebate dohvatiti. 
Napravite za svaki zahtjev koji vidite novi issue (npr. treba spremiti podatke: naziv, porodica... u tablicu ...)

**Comment by vdavid033** [comment]
#60 
@tcolic  - testirati!

**Comment by tcolic** [comment]
@vdavid033 testiranje je u procesu.

**Comment by tcolic** [comment]
[Testiranje sustava.docx](https://github.com/vdavid033/biljnevrste_repo/files/3256243/Testiranje.sustava.docx)

Kratak opis za svaki dio.. uglavnom za svaki vrijedi isto.

**Comment by vdavid033** [comment]
@tcolic  - Ok. Postaviti kao novi issue...

**Comment by vdavid033** [comment]
Spajanje na API je riješeno u:
[https://github.com/vdavid033/biljnevrste_repo/tree/frontend-merge-maria](https://github.com/vdavid033/biljnevrste_repo/tree/frontend-merge-maria)

Kad preuzmete, pogledajte pod projekt\frontend\src\pages\Kviz-Maracic2.vue
route: [http://localhost:8080/#/kviz2](http://localhost:8080/#/kviz2)  kad pokrenete **quasar dev**

Prebacite se na verziju quasara 1.0.0, ako još niste (@bmaracic?) .

**Comment by vdavid033** [comment]
@tcolic  - pogledat ćete mockup prozore i napraviti dizajn prema tome. Dio je odrađen. Trenutno je napravljen meni u template-u:  unos, pregled, kviz - to nemojte dirati. Instalirajte quasar (verzija 1.0.0-nešto). Pogledajte tutorijale dane na gornjim linkovima. Ne morate raditi vezivanje na bazu. Napravite samo dizajn na čisto. Nakon početne instalacije krenite od ovog:
[https://github.com/vdavid033/biljnevrste_repo/tree/tio-nio-patch-2](https://github.com/vdavid033/biljnevrste_repo/tree/tio-nio-patch-2)

**Comment by vdavid033** [comment]
@tcolic preuzmite, ubacite u svoj template: unos (@MariaMispi), pregled biljaka (@josipf09) , pregled detalja (@SaraMalesic) , kviz1 i kviz2 (@bmaracic) .
Zajedno sredite da su sve datoteke unutar /pages, te podesite routes.js datoteku
