### ISSUE TITLE
Odabire li student sam tip kviza ili mu se nasumično dodijeli tip kviza?

### ISSUE THREAD

**Issue by MariaMispi** [vdavid033/biljnevrste_repo#5]
Odabire li student sam tip kviza ili mu se nasumično dodijeli tip kviza?

_Originally posted by @MariaMispi in https://github.com/vdavid033/biljnevrste_repo/issues/4#issuecomment-478620484_

**Comment by fures404** [comment]
Nasumična dodjela tipa kviza.

**Comment by bmaracic** [comment]
Nema vrste kviza, jedan je kviz,
postoje dvije vrste pitanja koja se postavljaju nasumično:
prepoznavanje slike ili prepoznavanje naziva.

**Comment by Nikola9900** [comment]
Kviz će biti RANDOM.

**Comment by SamantaMalesic** [comment]
Tip kviza se dodjeljuje nasumično studentu.

**Comment by tcolic** [comment]
Ako je već kviz onda bi bilo bolje da je nasumično.

**Comment by karolina444** [comment]
Kviz se dodjeljuje nasumično

**Comment by tcolic** [comment]
S obzirom da kviz predstavlja provjeru znanja bilo bi dobro da bude i prepoznavanje slike i prepoznavanje naziva nasumično.
