### ISSUE TITLE
Backend setup i zadaci

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#53]
Backend: 

1. Instalirati i postaviti Django i REST framework (Python).
Za instalaciju koristiti _pip_ - Python package manager
_pip install django_
_pip install djangorestframework_

1. Paket za spajanje na MySQL (veleri):
_pip install mysql-connector-python_ 
ili lokalno
_pip install mysqlclient_

1. Kreiranje projekta i aplikacije: preuzimanje s glavnog repozitorija.

1. Startanje servera:
_python manage.py runserver_
i testiranje: 
_http://127.0.0.1:8000/_

1. Tutorijali:
[https://www.youtube.com/watch?v=D6esTdOLXh4](https://www.youtube.com/watch?v=D6esTdOLXh4)
[https://www.django-rest-framework.org/tutorial/quickstart/](https://www.django-rest-framework.org/tutorial/quickstart/)

1. Kreirati REST API-je:
@toni4848 - 
@SamantaMalesic - 
@bsvetlici 
@rkozlovic 
@IMilja

**Comment by bsvetlici** [comment]
Riješeno -upload za slike

**Comment by vdavid033** [comment]
za slike - python installl Pillow
Koji modul uključiti za naše znakove?

**Comment by vdavid033** [comment]
Stara verzija bez slika se spaja na bazu iooa-biljnedev9.
Popunjena je podacima, ali slike tamo još nisu riješene.
Verzija sa slikama je na portu 8001 i spaja se na iooa-biljnedev7.

Obje verzije su manjkave dok se ne riješi:
1. #70 
2. encoding

Molim odgovor!

**Comment by bsvetlici** [comment]
https://docs.djangoproject.com/en/2.2/ref/unicode/
Potrebno je staviti za naše znakove č, ć .... 
UTF-8 on bi trebao podržavati naše znakove na bazi jer navodno django na temelju toga generira automatski

također pronašao sam i ovo za dekodiranje

import codecs
f1 = codecs.open("croatian.txt", "r", "utf-8")
