### ISSUE TITLE
API na serveru 

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#55]
Live testiranje:

[http://193.198.97.14:8000/api/](http://193.198.97.14:8000/api/)

:-)

**Comment by vdavid033** [comment]
Ekipa na backendu (@SamantaMalesic, @bsvetlici, @rkozlovic, @toni4848, @IMilja): popunite testnim podacima
Ekipa na frontendu (@SaraMalesic, @bmaracic, @josipf09, @tcolic, @tio-nio, @MariaMispi, @Nikola9900, @karolina444): slobodno testirajte API

**Comment by IMilja** [comment]
#### Podatci za pristup "/admin" ako se javi potreba:
##### Username: admin
##### Password: admin123

**Comment by vdavid033** [comment]
Javite mi koja se greška pojavila kod dohvata podataka

**Comment by vdavid033** [comment]
Sa slikama:
http://193.198.97.14:8001/api/

**Comment by vdavid033** [comment]
Postavljena je nova verzija u kojoj se mogu dohvatiti i postaviti slike:
[http://193.198.97.14:8000/api/](http://193.198.97.14:8000/api/)
Baza je iooa-biljnedev4 i napunjena je testnim podacima
