### ISSUE TITLE
Koliko pitanja ima jedan kviz?

### ISSUE THREAD

**Issue by MariaMispi** [vdavid033/biljnevrste_repo#6]
Koliko pitanja ima jedan kviz?

_Originally posted by @MariaMispi in https://github.com/vdavid033/biljnevrste_repo/issues/4#issuecomment-478621010_

**Comment by rkozlovic** [comment]
10 pitanja

**Comment by karolina444** [comment]
5 pitanja

**Comment by bmaracic** [comment]
30 pitanja za provjeru znanja, neograničeno za vježbanje
