### ISSUE TITLE
Koliko će se slika prikazivati u kvizu - 10tak?

### ISSUE THREAD

**Issue by MariaMispi** [vdavid033/biljnevrste_repo#7]
Koliko će se slika prikazivati u kvizu - 10tak?

_Originally posted by @MariaMispi in https://github.com/vdavid033/biljnevrste_repo/issues/4#issuecomment-478621761_

**Comment by tio-nio** [comment]
5komada + mogucnost za dodavanje još (moze ih bit i 10ak)

**Comment by Nikola9900** [comment]
Mislim da smo govorili da će biti 5 slika.

**Comment by tcolic** [comment]
Možda radi preglednosti bi bilo bolje da ih je 6.

**Comment by MariaMispi** [comment]
5 slika.

**Comment by tonivkt** [comment]
10 je previse, 5 moze

**Comment by karolina444** [comment]
5

**Comment by tio-nio** [comment]
5 ih ide za unos ali nisu obavezne, šta ako neka biljka ima 3 slike? onda ce bit na kvizu samo te tri? možda da budu 5 glavnih odnosno prvih po redu

**Comment by SamantaMalesic** [comment]
5 slika

**Comment by bmaracic** [comment]
"po ponuđenom nazivu biljke student odabire sliku - prikazuje se jedna općenita slika za biljnu vrstu – jedna točna i npr.5 netočnih" - ovako je napisala profesorica

**Comment by SaraMalesic** [comment]
5
