### ISSUE TITLE
Greška u modelu podataka

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/biljnevrste_repo#70]
Ovo:
**Jedna botanička porodica može imati više rodova.**

Ispravite model -> ispravite backend -> upload nove verzije.

@tio-nio, @bsvetlici, @rkozlovic - ispravite model u dokumentaciji. Ponovno pročitajte specifikacije! Ispravite i opis!
@bsvetlici, @rkozlovic, @toni4848 - django rest! Ispravite i uploadajte novu verziju!

**Comment by vdavid033** [comment]
Predvidite više od 255 znakova za opis biljne vrste (do 2500).
@SamantaMalesic - provjerite obavezne/neobavezne unose prema dokumentaciji!

**Comment by tio-nio** [comment]
![baza_biljnevrste](https://user-images.githubusercontent.com/48513147/59203827-abce5d80-8b9f-11e9-98ae-5369893203ca.jpg)

**Comment by tio-nio** [comment]
pull request #72 i #73 @vdavid033

**Comment by vdavid033** [comment]
@rkozlovic @SamantaMalesic @bsvetlici @toni4848 također provjerite veličine polja za opis, te obavezne/neobavezne unose. Ovo odradite zajedno.
Prerađeni dump prethodne baze koji bi morao proći u novoj bazi kod importa: 

[iooa_biljnedev9.zip](https://github.com/vdavid033/biljnevrste_repo/files/3278581/iooa_biljnedev9.zip)

Kad se kreira baza, ove podatke morate ubaciti.

**Comment by vdavid033** [comment]
@tio-nio slika nije povezana s biljnom vrstom.... veza je samo nacrtana.

**Comment by vdavid033** [comment]
Postavljena nova verzija:
193.198.97.14:8000/api/
Baza je iooa-biljnedev4

**Comment by vdavid033** [comment]
@SamantaMalesic - provjerite bazu  
@tio-nio - ažurirajte dokumentaciju. 
Molim povratnu informaciju da ste to odradili.

**Comment by tio-nio** [comment]
![baza_biljnevrste](https://user-images.githubusercontent.com/48513147/59999299-ec2ee080-9661-11e9-85d9-0791b0ba8e11.jpg)

**Comment by tio-nio** [comment]
@vdavid033 ispravljeno, napravljen pull request

**Comment by SamantaMalesic** [comment]
Baza podataka je provjerena prema modelu podataka koji je izradio kolega Brusić. Sve je uredu, jedina je razlika što u bazi uporabni dio vrste ima i svoj vlastiti ID.
