### ISSUE TITLE
Ima li student uvid u ukupnu statistiku dosad rješenih kvizova?

### ISSUE THREAD

**Issue by MariaMispi** [vdavid033/biljnevrste_repo#8]
Ima li student uvid u ukupnu statistiku dosad rješenih kvizova?

_Originally posted by @MariaMispi in https://github.com/vdavid033/biljnevrste_repo/issues/4#issuecomment-478624119_

**Comment by IMilja** [comment]
Možda bi bilo dobro omogućiti da student prati svoje prijašnje rezultate kako bi znao koliko će otprilike dobiti bodova iz aktivnosti ovisno o svojim rezultatima kroz semestar.

**Comment by Nikola9900** [comment]
Na kraju svakog kviza ispisuje se rezultat.

**Comment by MariaMispi** [comment]
Klikom na gumb "Provjeri" dobija se povratna informacija o točnosti odgovora u obliku iksića ili kvačica u kvadratićima pored odgovora. Ukupna statistika dosada riješenih kvizova se za početak nigdje ne vodi.

**Comment by tcolic** [comment]
Na kraju svakog kviza korisnik može pregledati koja pitanja je riješio tačno ili netačno i ukupan broj bodova. Možda bi bilo dobro da ima neki high score memoriran tako da se motivira da bolje zna za sljedeći put.
