### ISSUE TITLE
Detalji biljke 

### ISSUE THREAD

**Issue by SaraMalesic** [vdavid033/biljnevrste_repo#81]
Kreiran prikaz detalja biljke #80  

Nedostaje ruta prema određenoj biljci

**Comment by vdavid033** [comment]
@tcolic - sredite dizajn prikaza i ubacite postojeći template.

**Comment by tcolic** [comment]
Dizajn je donekle riješen. Jedini je problem još ostao s tekstom slike kojeg nastojim riješiti.

**Comment by vdavid033** [comment]
@tcolic preuzmite, ubacite u svoj template i objavite
