### ISSUE TITLE
Pregled svih biljaka

### ISSUE THREAD

**Issue by fures404** [vdavid033/biljnevrste_repo#84]
#83
**Odrađeno je**: 
                     - Dohvaćanje podataka u tablicu prema izrađenom mockup-u, podaci su 
                        međusobno  povezani vanjskim ključevima
                     - Definiran je raposred podataka u tablici
                     - Izrađena je checkbox lista (uporabni dio) - nije povezana sa bazom
                     - Izrađen je search box
**Potrebno je**:
                    - pravilno pozicionirati tablicu (u ravnini sa uporabnim dijelom)
                    - kreirati rute prema prozoru za pregled pojedinih biljaka (pojedinačnim klikom na 
                       svaku biljku)

**Comment by vdavid033** [comment]
@tcolic - sredite dizajn i ubacite postojeći template.

**Comment by fures404** [comment]
Riješeno:
- pravilno pozicioniranje tablice
[https://github.com/josipf09/biljnevrste_repo/blob/master/projekt/frontend/pregled.vue]

Potrebno je:
-kreirati rute prema prozoru za pregled pojedinih biljaka (pojedinačnim klikom na
svaku biljku)

**Comment by tcolic** [comment]
Isprobano, sve je u redu.

**Comment by vdavid033** [comment]
@tcolic preuzmite, ubacite u svoj template i objavite
